
utilities:
  logger:
    name: UTILITIES
    logger_level: DEBUG
    format: "[%(name)s %(levelname)s] %(asctime)s - %(message)s"
    use_file_handler: false
    log_path: ""
    log_file_level: WARNING
    use_stream_handler: true

game:
  logger:
    name: GAME
    logger_level: INFO
    format: "[%(name)s %(levelname)s] %(asctime)s - %(message)s"
    use_file_handler: false
    log_path: ""
    log_file_level: DEBUG
    use_stream_handler: true

  run: {}

ai:
  logger:
    name: AI
    logger_level: INFO
    format: "[%(name)s %(levelname)s] %(asctime)s - %(message)s"
    use_file_handler: false
    log_path: ""
    log_file_level: WARNING
    use_stream_handler: true

  train: {}
